version: "3"
services:
    app:
        build:
            context: .
        image: iniquitybbs:edge
        ports: 
            - "22:22"
            - "23:23"
            - "80:80"
            - "443:443"
        volumes:
            - .:/iniquity