version: "3"
services:
    app:
        build:
            context: .
        image: iniquitybbs/iniquity:edge
        ports:
            - "22:22"
            - "23:23"
        volumes:
            - .:/iniquity
